version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.spring
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/it_db
      SPRING_DATASOURCE_USERNAME: it_user
      SPRING_DATASOURCE_PASSWORD: secret

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: it_db
      POSTGRES_USER: it_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: