WORKDIR /app
COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

# Mounted volume ersetzt den Code
# COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

CMD ["mvn", "spring-boot:run"]