version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.spring
    volumes:
      - ./src/main/java:/app/src/main/java
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./src/main/itcompany:/app    # Frontend Quellcode mounten

    environment:
      - CHOKIDAR_USEPOLLING=true
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data: