FROM oven/bun:latest
WORKDIR /app

COPY src/main/itcompany/package.json ./
COPY src/main/itcompany/bun.lock bun.lock
RUN bun install

COPY src/main/itcompany .

RUN bun run build

EXPOSE 3000
CMD ["bun", "dev"]